/*
    What the documentation page does once it is on screen: filter, copy, and keep the
    contents list pointing at wherever you are.

    Everything on the page is already in the HTML, generated by tools/build-docs.mjs.
    Nothing here fetches or builds anything, so the page is complete before this runs and
    reads the same to a search engine as it does to a person.
*/

"use strict";

(function () {
    const search = document.getElementById("search");
    const searchCount = document.getElementById("searchcount");
    const sections = [...document.querySelectorAll("section")];
    const items = [...document.querySelectorAll("ul.cmds li")].map((li) => ({
        el : li,
        // Matched against the command and against the symbol, so both '\to' and '→' find it
        text : (li.querySelector("code")?.textContent + " " +
                li.querySelector(".sym")?.textContent).toLowerCase()
    }));

    const empty = document.createElement("p");
    empty.id = "empty";
    empty.textContent = "No command and no symbol matches that.";
    document.querySelector("main").appendChild(empty);

    function filter(query) {
        const looked = query.trim().toLowerCase();
        document.body.classList.toggle("searching", looked !== "");

        if (looked === "") {
            for (const item of items) { item.el.classList.remove("hidden"); };
            for (const s of sections) { s.classList.remove("hidden"); };
            empty.classList.remove("shown");
            searchCount.textContent = "";
            return;
        };

        let shown = 0;
        for (const item of items) {
            const hit = item.text.includes(looked);
            item.el.classList.toggle("hidden", !hit);
            if (hit) { shown += 1; };
        };
        // A section with nothing left in it is noise, and so is the prose while searching
        for (const s of sections) {
            const list = s.querySelector("ul.cmds");
            s.classList.toggle("hidden",
                (!list) || (list.querySelectorAll("li:not(.hidden)").length === 0));
        };
        empty.classList.toggle("shown", shown === 0);
        searchCount.textContent = shown + ((shown === 1) ? " command" : " commands");
    };

    search.addEventListener("input", () => filter(search.value));

    // '/' puts the cursor in the search box, the way it does in a lot of documentation
    document.addEventListener("keydown", (e) => {
        if ((e.key === "/") && (document.activeElement !== search)) {
            e.preventDefault();
            search.focus();
            search.select();
        } else if ((e.key === "Escape") && (document.activeElement === search)) {
            search.value = "";
            filter("");
        };
    });

    // Clicking a symbol copies it, which is what most visits are for
    function copy(el) {
        const symbol = el.textContent;
        navigator.clipboard.writeText(symbol).then(() => {
            const was = el.textContent;
            el.classList.add("copied");
            el.textContent = "copied";
            setTimeout(() => {
                el.textContent = was;
                el.classList.remove("copied");
            }, 700);
        }, () => {});
    };

    document.addEventListener("click", (e) => {
        const sym = e.target.closest(".sym");
        if (sym) { copy(sym); };
    });
    document.addEventListener("keydown", (e) => {
        if (((e.key === "Enter") || (e.key === " ")) && (document.activeElement.classList?.contains("sym"))) {
            e.preventDefault();
            copy(document.activeElement);
        };
    });

    // The contents list follows the reading position
    const links = new Map();
    for (const a of document.querySelectorAll("#toc a")) {
        links.set(a.getAttribute("href").slice(1), a);
    };
    const spy = new IntersectionObserver((entries) => {
        for (const entry of entries) {
            if (!entry.isIntersecting) { continue; };
            for (const a of links.values()) { a.classList.remove("here"); };
            links.get(entry.target.id)?.classList.add("here");
        };
    }, { rootMargin: "0px 0px -75% 0px" });
    for (const s of sections) {
        if (s.id) { spy.observe(s); };
    };
})();
